Fix numpy bug
biosimulators/Biosimulators_utils pull request #122
Opened 2022-11-28 22:45 UTC by eagmon

This PR was previously opened with a different branch #121. This PR fixes a long-standing NumPy error in which a slice object can no longer be used as an index. Instead, I am pulling the ranges out of the slice object and using them directly.

I also fixed some listing errors and matplotlib deprecation errors, but left 4 tests still failing, down from 13 failing before this PR:

FAILED tests/model_lang/bngl/test_bngl_utils.py::BgnlUtilsTestCase::test_get_parameters_variables_for_simulation_with_empty_sample_times - AssertionError: “failed to parse action” does not match “Model file /home/runner/work/Biosimulators_utils/Biosimulators_utils/tests/model_lang/bngl/../../fixtures/bngl/empty-sample-times.bngl is not a valid BNGL or BNGL XML file.
FAILED tests/sedml/test_sedml_validation.py::ValidationTestCase::test_validate_calculation - AssertionError: ‘The syntax’ not found in ‘- The mathematical expression a * is invalid.\n - unexpected EOF while parsing (, line 1)’
FAILED tests/combine/test_combine_exec.py::ExecCombineTestCase::test_1 - AssertionError: None != {‘sim.sedml’: {‘report1’: ‘ABC’, ‘report2’: ‘DEF’}}
FAILED tests/combine/test_combine_exec.py::ExecCombineTestCase::test_2 - AssertionError: Lists differ: [‘log.yml’] != [‘dir1’, ‘log.yml’, ‘plots.zip’, ‘reports.zip’]

2022-11-29 15:29 UTC, CodeByDrescher commented
I found an alternate solution to fix the numpy bug; turns out multi-dimensional indexing still works if its done using a tuple. We don't need the slices to be mutable, so a cast to tuple worked just fine for our purposes.

2022-11-29 17:20 UTC, eagmon commented
nice find @CodeByDrescher! Looks like the NumPy bug is fixed. There are still 4 tests failing, but maybe those should be addressed in a separate PR?

2022-11-30 14:40 UTC, jcschaff approved these changes
approved, I like the tuple solution for numpy.

2022-11-30 14:41 UTC, jcschaff requested changes
can we fix the CI actions?

2022-11-30 14:47 UTC, eagmon commented
@jcschaff -- there are 4 failing tests left. Maybe we divide and conquer? We could also do that in a separate PR if we just want to get the NumPy bug fixed now to unblock progress in the test suite.

2022-12-02 18:18 UTC, eagmon commented on biosimulators_utils/combine/validation.py
> +             formats_to_validate:"list[CombineArchiveContentFormat]"=[
what kind of type is this? a string?

2022-12-06 20:01 UTC, jcschaff commented on biosimulators_utils/combine/io.py
> +            zip_archive.extractall(path=out_dir)
reminder to send bug report to  libcombine

2022-12-06 20:55 UTC, jcschaff commented on docs-src/requirements.txt
> +sphinxprettysearchresults @ git+https://github.com/biosimulators/sphinx-pretty-searchresults.git
add issue to sphinxprettysearchresults to add an import os (so we don't need the fork).

2022-12-06 21:14 UTC, jcschaff approved these changes
Great job, it works.  Logan discovered issues with two libraries and sent/will send notes to the authors.

2022-12-06 21:17 UTC, merged